In [2]:
from itertools import permutations, product
import math 

import pandas as pd

With repetition of digits allowed, there are 
10 x 10 x 10 x 10 x 10 x 10 == 10**6 == 1 million possible codes.

If it's ok to have repeated digits that are *not* consecutive, then it gets a bit messy so easier to do it computationally...

In [5]:
digits = range(0,10)
code_length = 6
perm = pd.DataFrame(product(digits, repeat=code_length))

consecutive_check_columns = []
for i in range(code_length-1):
    col_name = f"{i}_{i+1}_diff_within_one"
    consecutive_check_columns.append(col_name)
    perm[col_name] = (perm[i] - perm[i+1]).abs() <= 1


perm["any_diff_within_one"] = perm[consecutive_check_columns].any(axis="columns")

perm_non_consecutive = perm.loc[perm["any_diff_within_one"]==False]

perm_non_consecutive

,0,1,2,3,4,5,0_1_diff_within_one,1_2_diff_within_one,2_3_diff_within_one,3_4_diff_within_one,4_5_diff_within_one,any_diff_within_one
20202,0,2,0,2,0,2,False,False,False,False,False,False
20203,0,2,0,2,0,3,False,False,False,False,False,False
20204,0,2,0,2,0,4,False,False,False,False,False,False
20205,0,2,0,2,0,5,False,False,False,False,False,False
20206,0,2,0,2,0,6,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
979793,9,7,9,7,9,3,False,False,False,False,False,False
979794,9,7,9,7,9,4,False,False,False,False,False,False
979795,9,7,9,7,9,5,False,False,False,False,False,False
979796,9,7,9,7,9,6,False,False,False,False,False,False
979797,9,7,9,7,9,7,False,False,False,False,False,False

The result, just under 200,000, is a bit bigger than 10 x 7 x 7 x 7 x 7 x 7 because 0 and 9 only have one adjacent number each.

If there's no repetition of digits allowed at all - even non-adjacently - then the number of possible codes falls even further:
10 * 9 * 8 * 7 * 6 * 5 == 10!/4! = 151,200 possible codes.

In [3]:
math.factorial(10) / math.factorial(4)

151200.0

And if there are no repeated digits *and* no consecutive digits, then the number of possible codes falls way down, to just over 40,000.

In [ ]:
digits = range(0,10)
code_length = 6
perm = pd.DataFrame(permutations(digits, r=code_length))

consecutive_check_columns = []
for i in range(code_length-1):
    col_name = f"{i}_{i+1}_consecutive"
    consecutive_check_columns.append(col_name)
    perm[col_name] = (perm[i] - perm[i+1]).abs() == 1


perm["any_consecutive"] = perm[consecutive_check_columns].any(axis="columns")

perm_non_consecutive = perm.loc[perm["any_consecutive"]==False]

perm_non_consecutive

,0,1,2,3,4,5,0_1_consecutive,1_2_consecutive,2_3_consecutive,3_4_consecutive,4_5_consecutive,any_consecutive
2100,0,2,4,1,3,5,False,False,False,False,False,False
2101,0,2,4,1,3,6,False,False,False,False,False,False
2102,0,2,4,1,3,7,False,False,False,False,False,False
2103,0,2,4,1,3,8,False,False,False,False,False,False
2104,0,2,4,1,3,9,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
149095,9,7,5,8,6,0,False,False,False,False,False,False
149096,9,7,5,8,6,1,False,False,False,False,False,False
149097,9,7,5,8,6,2,False,False,False,False,False,False
149098,9,7,5,8,6,3,False,False,False,False,False,False
149099,9,7,5,8,6,4,False,False,False,False,False,False